=pod

=head1 NAME

 ydate - calcula fechas n dias antes o despues

=head1 SYNOPSIS

 ydate

=head1 DESCRIPTION 
 
      
             SCRIPT:  ydate.sh
      
                USO:  ./ydate.sh [-d n] [aaaammdd]
      
        DESCRIPCION:  Obtiene la fecha anterior; por omision un dia, puede variar 
                      con -d numero_dias
           OPCIONES:  -d   Numero de dias atras
       DEPENDENCIAS:  ---
               BUGS:  ---
              NOTAS:  0 es igual a 1 en parametro -d
                URL:  http://petrohs.googlepages.com/ydate.sh
          VERSIONES:  20090130 0.0.2 PetrOHS Se rediseño para aceptar el parametro
                                     -d a fin de recorrer fechas mas rapido.
                      -------- 0.0.1 Carlos Aquiles Dominguez     Creacion. 
 
=head1 EXAMPLES

 ydate -d 10

=head1 AUTHOR

 Developed by 
   petrohs
   Carlos Dominguez
                      
=head1 BUGS


=cut
# vim: set ts=3 sw=3 sts=3 et si ai:
