=pod

=head1 NAME

 ydate - Calculate a date in the timeline by taking +-N days as parameter

=head1 SYNOPSIS

 ydate [ -d ] | [ --days=+|-N ] | --help

=head1 DESCRIPTION 
 
 Calculate a date in the timeline by taking +-N days as parameter
 Mandatory arguments:
       -d, --days=+N|-N                by default -1 day, otherwise +-N days
       -h, --help                      show help
       
 Report bugs to <petrohs(at) mail.com>
                                      
=head1 EXAMPLES

 andresaquino $> date "+%Y%m%d"
 20101216
                     
 andresaquino $> sh ydate.sh -d
 20101215

 andresaquino $> sh ydate.sh --days=-4
 20101212

 andresaquino $> sh ydate.sh --days=5
 20101221

=head1 AUTHOR

 Authors
   Carlos Aquiles < (at) mail.com>  
   PetrOHS <petrohs(at) mail.com>

 Maintainer
   Andres Aquino <andres.aquino(at) mail.com>

=head1 BUGS


=cut
# vim: set ts=3 sw=3 sts=3 et si ai:
